module.exports = {
  LETTER_CHECK: "LETTER_CHECK",
  LETTER_UNCHECK: "LETTER_UNCHECK",

  LETTER_FAV: "LETTER_FAV",
  LETTER_UNFAV: "LETTER_UNFAV",

  CHECK_FILTERED: "CHECK_FILTERED",
  UNCHECK_FILTERED: "UNCHECK_FILTERED",
  TOGGLE_CHECK_FILTERED: "TOGGLE_CHECK_FILTERED",
  CHECK_FAVED_FILTERED: "CHECK_FAVED_FILTERED",
  CHECK_UNFAVED_FILTERED: "CHECK_UNFAVED_FILTERED",
  CHECK_NEW_FILTERED: "CHECK_NEW_FILTERED",
  CHECK_NOT_NEW_FILTERED: "CHECK_NOT_NEW_FILTERED"

}
