module.exports = {
  LETTER_CHECK: "LETTER_CHECK",
  LETTER_UNCHECK: "LETTER_UNCHECK",

  LETTER_CHECK_ALL_IN_FOLDER: "LETTER_CHECK_ALL_IN_FOLDER",
  LETTER_CHECK_NONE_IN_FOLDER: "LETTER_CHECK_NONE_IN_FOLDER",

  LETTER_TOGGLE_CHECK_ALL: "LETTER_TOGGLE_CHECK_ALL",
  LETTER_TOGGLE_CHECK_ALL_IN_FOLDER: "LETTER_TOGGLE_CHECK_ALL_IN_FOLDER",

  LETTER_CHECK_FAVED_IN_FOLDER: "LETTER_CHECK_FAVED_IN_FOLDER",
  LETTER_CHECK_UNFAVED_IN_FOLDER: "LETTER_CHECK_UNFAVED_IN_FOLDER",

  LETTER_CHECK_NEW_IN_FOLDER: "LETTER_CHECK_NEW_IN_FOLDER",
  LETTER_CHECK_NOT_NEW_IN_FOLDER: "LETTER_CHECK_NOT_NEW_IN_FOLDER",
  
  LETTER_FAV: "LETTER_FAV",
  LETTER_UNFAV: "LETTER_UNFAV"
}
